from typing import Any

def get_logger(*args: Any, **kwargs: Any) -> Any: ...
def configure(*args: Any, **kwargs: Any) -> None: ...
def make_filtering_bound_logger(*args: Any, **kwargs: Any) -> Any: ...
def PrintLoggerFactory(*args: Any, **kwargs: Any) -> Any: ...

class _ProcessorModule:
    def add_log_level(self, *args: Any, **kwargs: Any) -> Any: ...
    def TimeStamper(self, *args: Any, **kwargs: Any) -> Any: ...
    def JSONRenderer(self, *args: Any, **kwargs: Any) -> Any: ...

class _DevModule:
    def ConsoleRenderer(self, *args: Any, **kwargs: Any) -> Any: ...

class _ContextVarsModule:
    def merge_contextvars(self, *args: Any, **kwargs: Any) -> Any: ...

processors: _ProcessorModule
dev: _DevModule
contextvars: _ContextVarsModule
